#!/bin/sh
# This is a wrapper around the compiler, to ensure that the code
# example run from the org-mode file are all linked with Spot.
#
# Also we save errors to org.errors, so that we can detect issues
# after org-mode has exported everything.  Otherwise these errors
# would go undetected.
../../libtool link g++  -fvisibility=hidden -fvisibility-inlines-hidden -DSPOT_BUILD -std=c++17 -g -O3 -ffast-math -fstrict-aliasing -fomit-frame-pointer  -DNDEBUG -Wall -Werror \
 -I/home/nissa/Documents/Thesis/MANUSCRIPT/bsaltic/spot -I/home/nissa/Documents/Thesis/MANUSCRIPT/bsaltic/spot -I/home/nissa/Documents/Thesis/MANUSCRIPT/bsaltic/spot/buddy/src \
 "$@" /home/nissa/Documents/Thesis/MANUSCRIPT/bsaltic/spot/spot/libspot.la \
      /home/nissa/Documents/Thesis/MANUSCRIPT/bsaltic/spot/buddy/src/libbddx.la 2> errors.$$
code=$?
if test $code -ne 0 && test -s errors.$$; then
    cat errors.$$ >>org.errors
    cat errors.$$ >&2
fi
rm -f errors.$$
exit $code
